Mes=int(input("Mes del Año"))
if Mes==1:
    print ("Enero")
    match Mes:
        case 1:
         print ("Invierno")
elif Mes==2:
   print ("Febrero")
   match Mes:
      case 2:
         print ("Invierno")
elif Mes==3:
   print ("Marzo")
   match Mes:
      case 3:
         print ("Primavera")
elif Mes==4:
   print ("Abril")
   match Mes:
      case 4:
         print ("Primavera")
elif Mes==5:
   print("Mayo")
   match Mes:
      case 5:
         print ("Primavera")
elif Mes==6:
   print ("Junio")
   match Mes:
      case 6:
         print ("Verano")
elif Mes==7:
   print ("Julio")
   match Mes:
      case 7:
         print ("Verano")
elif Mes==8:
   print ("Agosto")
   match Mes:
      case 8:
         print ("Verano")
elif Mes==9:
   print ("Septiembre")
   match Mes:
      case 9:
         print ("Otoño")
elif Mes==10:
   print ("Octubre")
   match Mes:
      case 10:
         print ("Otoño")
elif Mes==11:
   print ("Noviembre")
   match Mes:
      case 11:
         print ("Otoño")
elif Mes==12:
   print ("Diciembre")
   match Mes:
      case 12:
         print ("Invierno")